import Head from "next/head";
import ConnectButton from "../components/ConnectButton";
import styles from "../styles/Home.module.css";

const Home = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>My Next.js App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to My Next.js App</h1>
        <ConnectButton />
      </main>
    </div>
  );
};

export default Home;
