name: Smart Contract Tests
on: [push]
jobs:
  Unit tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./contracts
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install dependencies
        run: yarn
      - name: Test compile smart contracts
        run: yarn compile
      - name: Test deploy smart contracts
        run: yarn deploy
      - name: Test smart contracts
        run: yarn test
